#!/bin/sh
IP=192.168.1.144
PORT=49157
DIR=upnp/event/basicevent1
echo "Query $IP ..."
curl -v -0 -A '' -X SUBSCRIBE -H 'Accept: ' -H 'Content-type: text/xml; charset="utf-8"' \
    -H 'CALLBACK: "<http://192.168.1.176:1234/testupnp>"' \
    -H 'NT: upnp:event' \
    -H 'TIMEOUT: Second-600' \
    -s http://$IP:$PORT/$DIR
