#!/bin/sh
IP=192.168.1.100
PORT=80
echo "Query $IP ..."
curl -0 -A '' -X POST -H 'Accept: ' -H 'Content-type: text/xml; charset="utf-8"' \
    -H 'SOAPACTION: "urn:danny-backx-info:serviceId:BMP180#getState"' \
    --data '<?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><u:getState xmlns:u = "urn:upnp-org:serviceId:ContentDirectory"></u:getState></s:Body></s:Envelope>' \
    -s http://$IP:$PORT/PressureSensor/control
